//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJJ.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Deposits
    {
        public int deposit_id { get; set; }
        public string Id { get; set; }
        public short deposit_status { get; set; }
        public int charge_gold_value { get; set; }
        public double deposit_money_value { get; set; }
        public System.DateTime deposit_date_time { get; set; }
        public string deposit_tracking_code { get; set; }
        public string deposit_dest_account_number { get; set; }
        public string deposit_img { get; set; }
        public string deposit_comment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
