//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJJ.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Request_Money
    {
        public int req_id { get; set; }
        public string Id { get; set; }
        public short req_status { get; set; }
        public float sell_gold_value { get; set; }
        public double req_money_value { get; set; }
        public System.DateTime sell_date_time { get; set; }
        public string sell_tracking_code { get; set; }
        public string sell_dest_account_number { get; set; }
        public string sell_img { get; set; }
        public string sell_user_comment { get; set; }
        public string sell_admin_comment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
